name: Build Docker image and publish to ECR

on:
    push:
        branches:
            - main

jobs:
    deploy:
        name: Deploy to ECR
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ap-south-1

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v1

            - name: Check version
              uses: bbonkr/get-version-action@v1.0.4
              id: get_version
              with:
                  project: "./package.json"

            - name: Build, tag, and push the image to Amazon ECR
              id: build-image
              env:
                  ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                  ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY }}
                  IMAGE_TAG: ${{steps.get_version.outputs.version}}
              run: |
                  # Build a docker container and push it to ECR 
                  docker build -t image .
                  docker tag image:latest $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
                  echo "Pushing image to ECR..."
                  docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
                  echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
